import { NgModule } from '@angular/core';
import { SelectValueAccessor } from './directives/select-value-accessor.directive';
import { RadioGroupValueAccessor } from './directives/radio-group-value-accessor.directive';
import { CheckboxValueAccessorDirective } from './directives/checkbox-value-accessor.directive';
import { SwitchValueAccessorDirective } from './directives/switch-value-accessor.directive';
import { InputValueAccessorDirective } from './directives/input-value-accessor.directive';
import { TextareaValueAccessorDirective } from './directives/textarea-value-accessor.directive';
import { CounterValueAccessorDirective } from './directives/counter-value-accessor.directive';
import {
  WcsAlert,
  WcsAlertDrawer,
  WcsAccordion, WcsAccordionContent, WcsAccordionHeader, WcsAccordionPanel,
  WcsActionBar,
  WcsApp,
  WcsBadge,
  WcsBreadcrumb,
  WcsBreadcrumbItem,
  WcsButton,
  WcsCard,
  WcsCardBody,
  WcsCheckbox,
  WcsChip,
  WcsComNav,
  WcsComNavItem,
  WcsComNavCategory,
  WcsComNavSubmenu,
  WcsCounter,
  WcsDivider,
  WcsDropdown, WcsDropdownDivider, WcsDropdownHeader,
  WcsDropdownItem,
  WcsEditableField,
  WcsError,
  WcsField,
  WcsFieldContent,
  WcsFieldLabel,
  WcsFooter,
  WcsFormField,
  WcsGalactic,
  WcsGalacticMenu,
  WcsGrid,
  WcsGridColumn, WcsGridCustomCell,
  WcsGridPagination,
  WcsHeader,
  WcsHint,
  WcsHorizontalStepper,
  WcsIcon,
  WcsInput,
  WcsLabel,
  WcsListItem,
  WcsListItemProperties,
  WcsListItemProperty,
  WcsMatIcon,
  WcsModal,
  WcsNav,
  WcsNavItem,
  WcsProgressBar,
  WcsProgressRadial,
  WcsRadio,
  WcsRadioGroup,
  WcsSelect,
  WcsSelectOption,
  WcsSkeletonCircle,
  WcsSkeletonRectangle,
  WcsSkeletonText,
  WcsSpinner,
  WcsSwitch,
  WcsTab,
  WcsTabs,
  WcsTextarea,
  WcsTooltip,
  WcsNativeSelect,
  WcsCardContent,
  WcsCardHeader,
  WcsCardFooter,
  WcsCardMedia,
} from './proxies';
import { GridValueAccessorDirective } from './directives/grid-value-accessor.directive';

const DECLARATIONS = [
  WcsAlert,
  WcsAlertDrawer,
  WcsActionBar,
  WcsAccordion,
  WcsAccordionContent,
  WcsAccordionHeader,
  WcsAccordionPanel,
  WcsApp,
  WcsBadge,
  WcsBreadcrumb,
  WcsBreadcrumbItem,
  WcsButton,
  WcsCard,
  WcsCardBody,
  WcsCardHeader,
  WcsCardMedia,
  WcsCardContent,
  WcsCardFooter,
  WcsCheckbox,
  WcsChip,
  WcsComNav,
  WcsComNavItem,
  WcsComNavCategory,
  WcsComNavSubmenu,
  WcsCounter,
  WcsDivider,
  WcsDropdown,
  WcsDropdownDivider,
  WcsDropdownHeader,
  WcsDropdownItem,
  WcsEditableField,
  WcsError,
  WcsField,
  WcsFieldContent,
  WcsFieldLabel,
  WcsFooter,
  WcsFormField,
  WcsGalactic,
  WcsGalacticMenu,
  WcsGrid,
  WcsGridColumn,
  WcsGridCustomCell,
  WcsGridPagination,
  WcsHeader,
  WcsHint,
  WcsHorizontalStepper,
  WcsIcon,
  WcsInput,
  WcsLabel,
  WcsListItem,
  WcsListItemProperties,
  WcsListItemProperty,
  WcsMatIcon,
  WcsModal,
  WcsNav,
  WcsNavItem,
  WcsProgressBar,
  WcsProgressRadial,
  WcsRadio,
  WcsRadioGroup,
  WcsSelect,
  WcsSelectOption,
  WcsSkeletonCircle,
  WcsSkeletonRectangle,
  WcsSkeletonText,
  WcsSpinner,
  WcsSwitch,
  WcsTab,
  WcsTabs,
  WcsTextarea,
  WcsTooltip,
  WcsNativeSelect,
  // Value accessors
  InputValueAccessorDirective,
  TextareaValueAccessorDirective,
  SelectValueAccessor,
  RadioGroupValueAccessor,
  CheckboxValueAccessorDirective,
  SwitchValueAccessorDirective,
  CounterValueAccessorDirective,
  GridValueAccessorDirective,
];

@NgModule({
  declarations: DECLARATIONS,
  imports: [],
  exports: DECLARATIONS
})
export class WcsAngularModule {
}
