stages:
    - test
    - build
    - deploy

image: node:14-alpine

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/
    - angular/node_modules/

before_script:
    - npm install
    - cd angular/ && npm install && cd ../

test:
    image: buildkite/puppeteer
    stage: test
    script:
        - npm test

build:
    stage: build
    artifacts:
        expire_in: 4 days
        paths:
            - www/
            - loader/
            - schematics/
            - dist/
            - angular/dist/wcs-angular/
    script:
        - npm run build
        - cd angular/ && npm run build

pages:
    stage: deploy
    dependencies:
        - build
    only:
        - develop
    artifacts:
        expire_in: 4 days
        paths:
            - public
    script:
        - mkdir -p public/$CI_COMMIT_REF_NAME/
        - mv www/* public/$CI_COMMIT_REF_NAME/

publish:
    stage: deploy
    only:
        - tags
    except:
        - /^(?!master).+@/
    dependencies:
        - build
    script:
        - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        - npm publish
        - cd angular/dist/wcs-angular/ && echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc && npm publish
