stages:
    - test
    - build
    - deploy

test:
    image: markhobson/node-chrome
    stage: test
    before_script:
        - npm install
    cache:
        paths:
            - node_modules/
    script:
        - npm test

build:
    image: node:latest
    stage: build
    only:
        - develop
    artifacts:
        paths:
            - www/
    script:
        - npm install
        - npm run build
    cache:
        paths:
            - node_modules/

pages:
    image: node:latest
    stage: deploy
    dependencies:
        - build
    only:
        - develop
    cache:
        paths:
            - node_modules/
    script:
        - mv www/ public/
    artifacts:
        paths:
            - public
