stages:
    - test
    - deploy

test:
    image: markhobson/node-chrome
    stage: test
    before_script:
        - npm install
    cache:
        paths:
            - node_modules/
    script:
        - npm test

pages:
    image: node
    stage: deploy
    before_script:
        - npm install
    only:
        - develop
    cache:
        paths:
            - node_modules/

    script:
        - npm run-script build
    artifacts:
        paths:
            - www
