stages:
    - test
    - build
    - deploy

image: node:16-alpine

# Cache modules in between jobs: https://docs.gitlab.com/ee/ci/caching/#cache-nodejs-dependencies
# cache:
#   key: ${CI_COMMIT_REF_SLUG}
#   paths:
#     - node_modules/
#     - angular/node_modules/

cache:
    paths:
        - doc_cache

before_script:
    - npm install
    - cd angular/ && npm install && cd ../

test:
    tags:
        - sncf-runner-1
    image: buildkite/puppeteer:5.2.1
    stage: test
    script:
        - npm test

build:
    tags:
        - sncf-runner-1
    stage: build
    artifacts:
        expire_in: 4 days
        paths:
            - storybook-static/
            - loader/
            - dist/
            - angular/dist/wcs-angular/
            - angular/dist/wcs-formly/
    script:
        - npm run build
        - cd angular/
        - npm run build --configuration production wcs-angular
        - npm run build --configuration production wcs-formly

pages:
    tags:
        - gitlab-org
    stage: deploy
    dependencies:
        - build
    only:
        - develop
        - master
    artifacts:
        expire_in: 4 days
        paths:
            - public
    script:
        - mkdir -p doc_cache/$CI_COMMIT_REF_NAME/
        - rm -rf doc_cache/$CI_COMMIT_REF_NAME/*
        - cp -r storybook-static/* doc_cache/$CI_COMMIT_REF_NAME/
        - cp -r doc_cache public

# PUBLISH PACKAGES FOR TAGS
publish-wcs-core:
    tags:
        - sncf-runner-1
    stage: deploy
    only:
        - tags
    dependencies:
        - build
    script:
        - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc && npm publish
publish-wcs-angular:
    tags:
        - sncf-runner-1
    stage: deploy
    only:
        - tags
    dependencies:
        - build
    script:
        - cd angular/dist/wcs-angular/ && echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc && npm publish
publish-wcs-formly:
    tags:
        - sncf-runner-1
    stage: deploy
    only:
        - tags
    dependencies:
        - build
    script:
        - cd angular/dist/wcs-formly/ && echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc && npm publish
