stages:
    - test
    - build
    - deploy

image: node:12.9-alpine

# Cache modules in between jobs
cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
    - node_modules/

before_script:
    - npm install

test:
    image: markhobson/node-chrome
    stage: test
    script:
        - npm test

build:
    stage: build
    only:
        - develop
        - tags
    artifacts:
        expire_in: 4 days
        paths:
            - www/
            - loader/
            - dist/
    script:
        - npm run build

pages:
    stage: deploy
    dependencies:
        - build
    only:
        - develop
    artifacts:
        expire_in: 4 days
        paths:
            - public
    script:
        - mkdir -p public/$CI_COMMIT_REF_NAME/
        - mv www public/$CI_COMMIT_REF_NAME/

publish:
    stage: deploy
    only:
        - tags
    except:
        - /^(?!master).+@/
    dependencies:
        - build
    script:
        - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        - npm publish
