stages:
    - test
    - build
    - deploy

image: node:14-alpine

# Cache modules in between jobs
# cache:
#   key: ${CI_COMMIT_REF_SLUG}
#   paths:
#     - node_modules/
#     - angular/node_modules/

before_script:
    - npm install
    - cd angular/ && npm install && cd ../

test:
    tags:
        - sncf-runner-1
    image: buildkite/puppeteer:5.2.1
    stage: test
    script:
        - npm test

build:
    tags:
        - sncf-runner-1
    stage: build
    artifacts:
        expire_in: 4 days
        paths:
            - www/
            - loader/
            - schematics/
            - dist/
            - angular/dist/wcs-angular/
            - angular/dist/wcs-formly/
    script:
        - npm run build
        - cd angular/
        - npm run build wcs-angular
        - npm run build wcs-formly

pages:
    tags:
        - gitlab-org
    stage: deploy
    dependencies:
        - build
    only:
        - develop
        - master
    artifacts:
        expire_in: 4 days
        paths:
            - public
    script:
        - mkdir -p cache/$CI_COMMIT_REF_NAME/
        - rm -rf cache/$CI_COMMIT_BRANCH/*
        - cp -r www/* cache/$CI_COMMIT_REF_NAME/
        - cp -r cache public

publish:
    tags:
        - sncf-runner-1
    stage: deploy
    only:
        - tags
    except:
        - /^(?!master).+@/
    dependencies:
        - build
    script:
        - echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc
        - npm publish
        - cd angular/dist/wcs-angular/ && echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc && npm publish
        - cd .. && cd wcs-formly/ && echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > .npmrc && npm publish
